# Generated by Django 5.1.1 on 2024-11-18 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('top_tracks', models.JSONField()),
                ('top_artists', models.JSONField()),
                ('top_genre', models.CharField(max_length=255)),
                ('new_artists_count', models.IntegerField()),
                ('personality_insights', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spotify Wrap',
                'verbose_name_plural': 'Spotify Wraps',
                'ordering': ['-created_at'],
            },
        ),
    ]
