# Generated by Django 5.1 on 2024-11-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_auth', '0002_spotifywrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrap',
            name='genre_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='total_unique_genres',
            field=models.IntegerField(default=0),
        ),
    ]
