# Generated by Django 5.1.1 on 2024-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_auth', '0003_spotifywrap_genre_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrap',
            name='time_range',
            field=models.CharField(choices=[('short_term', 'Short Term (Last 4 Weeks)'), ('medium_term', 'Medium Term (Last 6 Months)'), ('long_term', 'Long Term (All Time)')], default='medium_term', max_length=20),
        ),
    ]
